[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["../../node_modules"]
fs_permissions = [{ access = "read-write", path = "./script/VaultData"}]
via_ir = true
evm_version = "paris"
# TODO: Enable before pushing to main
optimizer = false
optimizer_runs = 20_000
solc = "0.8.25"
runs = 100000

[invariant]
fail_on_revert = true